In [ ]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

from modules.utils.transformer import Normalization
Normalization(pos)

array([[ 0.        ,  0.46291005],
       [ 1.22474487, -1.38873015],
       [-1.22474487,  0.9258201 ]])

In [51]:
# distance_matrix()

import numpy as np 

pos = np.array([[2, 5],
                [3, 1],
                [1, 6],])
dim = len(pos)

D = np.zeros((dim, dim))
for i in range(dim):
    for j in range(i+1, dim):
        print(pos[i], pos[j])
        dist = np.linalg.norm(pos[i]-pos[j])
        D[i][j] = D[j][i] = dist

D

[2 5] [3 1]
[2 5] [1 6]
[3 1] [1 6]


array([[0.        , 4.12310563, 1.41421356],
       [4.12310563, 0.        , 5.38516481],
       [1.41421356, 5.38516481, 0.        ]])

In [52]:
# _I()
def _I():
    return np.identity(dim)

In [53]:
# _J()
def _J():
    return np.ones((dim, dim))

In [54]:
# Double Centering
U = _I() - (1/dim)*_J()
Z = -(1/2) * (U @ D @ U)

print(U)
print()
print(Z)

[[ 0.66666667 -0.33333333 -0.33333333]
 [-0.33333333  0.66666667 -0.33333333]
 [-0.33333333 -0.33333333  0.66666667]]

[[ 0.63216373 -0.76756388  0.13540015]
 [-0.76756388  1.95581414 -1.18825027]
 [ 0.13540015 -1.18825027  1.05285012]]


In [55]:
# Eckart-Young decomposition
eigenvalues, eigenvectors = np.linalg.eig(Z)
print(eigenvalues)
print()
print(eigenvectors)
print()

Lambda = np.diag(eigenvalues)
print(Lambda)

[ 2.99181732e+00  6.49010677e-01 -3.74772679e-17]

[[-0.2918047   0.76257241  0.57735027]
 [ 0.80630943 -0.12857592  0.57735027]
 [-0.51450473 -0.63399649  0.57735027]]

[[ 2.99181732e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  6.49010677e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.74772679e-17]]


In [57]:
np.sqrt(Lambda)

/var/folders/_z/nvf0bn013y300yf072lzgkgw0000gn/T/ipykernel_17737/851418910.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(Lambda)


array([[1.72968706, 0.        , 0.        ],
       [0.        , 0.80561199, 0.        ],
       [0.        , 0.        ,        nan]])