In [1]:
import sys
from pathlib import Path
PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

import numpy as np

from modules.MDS import MultiDimensionalScaler, squared_distance_matrix

In [2]:
D2 = np.asarray([[0, 5],
                 [5, 0],])

mds = MultiDimensionalScaler(D2)


# 次元削減後の座標
new_axis = mds.embed()
print(new_axis)

print()

# 次元削減後の座標の次元
dim = mds.minimal_dimension()
print(f"次元削減後の座標の次元 : {dim}")

[[-1.11803399]
 [ 1.11803399]]

次元削減後の座標の次元 : 1


In [3]:
import pandas as pd
import numpy as np

data = [{"id": 1, "data_A": 1, "data_B": 3, "data_C": 0},
        {"id": 2, "data_A": 3, "data_B": 2, "data_C": -4},
        {"id": 3, "data_A": 3, "data_B": 4, "data_C": -1},
        {"id": 4, "data_A": 2, "data_B": 2, "data_C": 0},
        {"id": 5, "data_A": 4, "data_B": 1, "data_C": 3},
        ]

df = pd.DataFrame(data)
pos = np.asarray(df[["data_A", "data_B", "data_C"]])
D2 = squared_distance_matrix(pos)

mds = MultiDimensionalScaler(D2)
# 次元削減後の座標
new_axis = mds.embed()
print(new_axis)

print()

# 次元削減後の座標の次元
dim = mds.minimal_dimension()
print(f"次元削減後の座標の次元 : {dim}")

[[-0.06952143  1.66589633 -0.54768255]
 [ 3.3645682  -1.36055724 -0.3294918 ]
 [ 0.86232504  0.55254728  1.42516211]
 [-0.39719438  0.2947451  -0.65981964]
 [-3.76017743 -1.15263147  0.11183187]]

次元削減後の座標の次元 : 3
